hitvmm/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^index/$', views.index,name='index'),
    url(r'^login/$', views.login,name='login'),
    url(r'^login/action$', views.login_action,name='login_action'),
    url(r'^exp/prev/(?P<v_id>[0-9]+)$', views.exp_pre_v,name='exp_pre_v'),
    url(r'^exp/opr/$', views.exp_opr,name='exp_opr'),
    url(r'^report$', views.report,name='report'),
    url(r'^upload_ajax/$', views.upload_ajax,name='upload_ajax'),
    url(r'^report/correct$', views.report_correct,name='report_correct'),
    url(r'^report/correct/(?P<v_id>[0-9]+)$', views.report_correct_view,name='report_correct_view'),


    #老师提交分数
    url(r'^score_ajax/$', views.score_ajax,name='score_ajax'),

    #实验准备页面1,2,3
    url(r'^exp/opr/1$', views.exp_opr_1_1,name='exp_opr_1_1'),
    url(r'^exp/opr/2$', views.exp_opr_2_1,name='exp_opr_2_1'),
    url(r'^exp/opr/3$', views.exp_opr_3_1,name='exp_opr_3_1'),

    #实验操作第1步
    url(r'^exp/opr/1/1/$', views.exp_opr_1_2,name='exp_opr_1_2'),
    url(r'^exp/opr/2/1/$', views.exp_opr_2_2,name='exp_opr_2_2'),
    url(r'^exp/opr/3/1/$', views.exp_opr_3_2,name='exp_opr_3_2'),

    #实验操作第2步
    url(r'^exp/opr/1/2$', views.exp_opr_1_3,name='exp_opr_1_3'),
    url(r'^exp/opr/2/2$', views.exp_opr_2_3,name='exp_opr_2_3'),

    #实验操作第3步
    url(r'^exp/opr/1/3$', views.exp_opr_1_4,name='exp_opr_1_4'),
    url(r'^exp/opr/2/3$', views.exp_opr_2_4,name='exp_opr_2_4'),


]

vmm/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^hitvmm/',include('hitvmm.urls',namespace='hitvmm')),
    url(r'^static/(?P<path>.*)$', static.serve, {'document_root': settings.STATIC_ROOT }, name='static'),
]

hitvmm/models.py
from django.db import models
import django.utils.timezone as timezone


#用户表
class User(models.Model):
    name=models.CharField(max_length=64)
    password=models.CharField(max_length=64)
    school=models.CharField(max_length=64,default="free")

    #学生为1，老师为2
    identity=models.CharField(max_length=32,default="1")
    create_time=models.DateTimeField(default=timezone.now)

#班级表
class TeamRecord(models.Model):
    team_name=models.CharField(max_length=64,default="free_team")
    school=models.CharField(max_length=64,default="free_school")
    experiment_id=models.IntegerField(default=0)
    teacher_id=models.IntegerField(default=0)
    student_id=models.IntegerField(default=0)
    create_time=models.DateTimeField(default=timezone.now)

#报告表
class ReportRecord(models.Model):
    #对应实验ID
    experiment_id=models.IntegerField(default=0)
    #老师ID
    teacher_id=models.IntegerField(default=0)
    #老师姓名
    teacher_name=models.CharField(max_length=32,default="free")
    #学生ID
    student_id=models.IntegerField(default=0)
    #学生姓名
    student_name=models.CharField(max_length=32,default="free")
    #学生学号
    student_password=models.CharField(max_length=32,default="free")
    #报告提交时间
    subm_time=models.DateTimeField(default=timezone.now)
    #报告批改时间
    score_time=models.DateTimeField(default=timezone.now)
    #报告分数
    score=models.IntegerField(default=0)
    #报告批阅状态，false为未批改，ture为批改
    tatus=models.BooleanField(default=False)
    #时间戳
    timestamp=models.CharField(max_length=32,default="")

hitvmm/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import models

#检验用户是否已经登录
#def login_test(request):
#    name=request.COOKIES.get('name')
#    password=request.COOKIES.get('password')
#    student_id=request.COOKIES.get('student_id')
#    if not name and password and student_id:
#        return render(request,'hitvmm/login.html')



def index(request):
    name=request.COOKIES.get('name')
    if not name:
        return render(request,'hitvmm/login.html')
    password=request.COOKIES.get('password')
    user_id=str(request.COOKIES.get('user_id'))


    return render(request,'hitvmm/index.html',{'name':name,'password':password,})

def login(request):
    return render(request,'hitvmm/login.html')

def login_action(request):
    name=request.POST.get('name','NAME')
    password=request.POST.get('password','PASSWORD')
    try:
        user_test= models.User.objects.get(name=name)
    except:
        return render(request,'hitvmm/login.html',{'hint':'*姓名不存在','name':name,'password':password})

    if name==user_test.name and password==user_test.password:
        #取到学生的ID
        human = models.User.objects.get(name=name,password=password)
        user_id=human.id
        ret= render(request,'hitvmm/toindex.html')

        #判断是不是为老师
        if human.identity=='2':
            ret= render(request,'hitvmm/toreport_correct.html')
        #将ID、姓名和学号加入缓存
        ret.set_cookie('name', name)
        ret.set_cookie('password', password)
        ret.set_cookie('user_id', user_id)
        return ret

    else:
        return render(request,'hitvmm/login.html',{'hint':'*密码错误','name':name,'password':password})

def exp_pre_v(request,v_id):
    name=request.COOKIES.get('name')
    if not name:
        return render(request,'hitvmm/login.html')
    password=request.COOKIES.get('password')
    user_id=str(request.COOKIES.get('user_id'))
    reports=models.ReportRecord.objects.filter(student_id=user_id)

    return render(request,'hitvmm/exp_pre_v.html',{'v_id':v_id,'name':name,'password':password,})

#打开实验操作页面
def exp_opr(request):
    name=request.COOKIES.get('name')
    if not name:
        return render(request,'hitvmm/login.html')
    password=request.COOKIES.get('password')
    user_id=str(request.COOKIES.get('user_id'))
    reports=models.ReportRecord.objects.filter(student_id=user_id)

    return render(request,'hitvmm/exp_opr.html',{'name':name,'password':password,})

#打开报告提交页面
def report(request):
    name=request.COOKIES.get('name')
    if not name:
        return render(request,'hitvmm/login.html')
    password=request.COOKIES.get('password')
    user_id=str(request.COOKIES.get('user_id'))
    reports=models.ReportRecord.objects.filter(student_id=user_id)

    return render(request,'hitvmm/report.html',{'name':name,'password':password,'reports':reports,'student_id':user_id})

#学生上传报告
def upload_ajax(request):
    if request.method == 'POST':
        file_obj = request.FILES.get('file')
        new_file_name=request.POST.get('new_file_name')
        name=request.POST.get('name')
        password=request.POST.get('password')
        user_id=request.POST.get('user_id')
        experiment_id=request.POST.get('experiment_id')
        timestamp=request.POST.get('timestamp')

        team=models.TeamRecord.objects.get(student_id=user_id,experiment_id=experiment_id)
        teacher_id=team.teacher_id
        teacher_name=models.User.objects.get(pk=teacher_id).name

        models.ReportRecord.objects.create(timestamp=timestamp,teacher_name=teacher_name,teacher_id=teacher_id,student_id=user_id,student_name=name,student_password=password,experiment_id=experiment_id)


        import os
        f = open(os.path.join('static', 'reports', new_file_name), 'wb')
        print(file_obj,type(file_obj))
        for chunk in file_obj.chunks():
            f.write(chunk)
        f.close()

        return HttpResponse('OK')

#老师浏览待批阅报告
def report_correct(request):
    name=request.COOKIES.get('name')
    if not name:
        return render(request,'hitvmm/login.html')
    password=request.COOKIES.get('password')
    user_id=str(request.COOKIES.get('user_id'))

    reports=models.ReportRecord.objects.filter(teacher_id=user_id,tatus=False)

    return render(request,'hitvmm/report_correct.html',{'name':name,'password':password,'user':user_id,'reports':reports})



# 老师批阅报告
def report_correct_view(request,v_id):
    name=request.COOKIES.get('name')
    if not name:
        return render(request,'hitvmm/login.html')
    password=request.COOKIES.get('password')
    user_id=str(request.COOKIES.get('user_id'))

    report=models.ReportRecord.objects.get(pk=v_id)
    s=report.experiment_id
    file_name='reports/'+str(s)+'_'+report.student_name+'_'+report.student_password+'_'+report.timestamp+'.pdf'
    return render(request,'hitvmm/report_correct_view.html',{'file_name':file_name,'name':name,'password':password,'user':user_id,'report_id':v_id})

#老师提交分数
def score_ajax(request):
    if request.method == 'POST':
        score=request.POST.get('score')
        report_id=request.POST.get('report_id')
        report=models.ReportRecord.objects.get(pk=report_id)
        report.score=score
        report.tatus=True
        report.save()
        return HttpResponse('OK')

#实验准备页面
def exp_opr_1_1(request):
    return render(request,'hitvmm/exp_1_1.html')

def exp_opr_2_1(request):
    return render(request,'hitvmm/exp_2_1.html')

def exp_opr_3_1(request):
    return render(request,'hitvmm/exp_3_1.html')


#实验操作第一步页面
def exp_opr_1_2(request):

    cfc=1;
    xfc=1;
    yfc=1;
    kkfc=1;
    klfc=1;
    knfc=1;
    krfc=1;

    #根据加工形式调整参数
    machining_form=request.POST.get('machining_form')
    if machining_form=="a":
        cfc=180
        xfc=1
        yfc=0.75
    elif machining_form=="b":
        cfc=222
        xfc=1
        yfc=1
    else :
        cfc=191
        xfc=1
        yfc=0.75

    #根据主偏角调整参数
    main_arc=request.POST.get('main_arc')
    if main_arc=="a":
        kkfc=1.08
    elif main_arc=="b":
        kkfc=1
    elif main_arc=="c":
        kkfc=0.94
    elif main_arc=="d":
        kkfc=0.92
    else :
        kkfc=0.89

    #根据刀具前角调整参数
    front_arc=request.POST.get('front_arc')
    if front_arc=="a":
        klfc=1.25
    elif front_arc=="b":
        klfc=1.2
    elif front_arc=="c":
        klfc=1.1
    elif front_arc=="d":
        klfc=1
    else :
        klfc=0.9

    name=request.COOKIES.get('name')
    password=request.COOKIES.get('password')

    ret=render(request,'hitvmm/exp_1_2.html',{'cfc':cfc,'xfc':xfc,'yfc':yfc,'kkfc':kkfc,'klfc':klfc,'knfc':knfc,'krfc':krfc,'name':name,'password':password})
    #将参数存进cookie
    ret.set_cookie('cfc', cfc)
    ret.set_cookie('xfc', xfc)
    ret.set_cookie('yfc', yfc)
    ret.set_cookie('kkfc', kkfc)
    ret.set_cookie('klfc', klfc)
    ret.set_cookie('knfc', knfc)
    ret.set_cookie('krfc', krfc)

    return ret

    #实验操作第一步页面
    # def exp_opr_1_2(request,exp_id):
    #
    #     cfc=1;
    #     xfc=1;
    #     yfc=1;
    #     kkfc=1;
    #     klfc=1;
    #     knfc=1;
    #     krfc=1;
    #
    #     #根据加工形式调整参数
    #     machining_form=request.POST.get('machining_form')
    #     if machining_form=="a":
    #         cfc=180
    #         xfc=1
    #         yfc=0.75
    #     elif machining_form=="b":
    #         cfc=222
    #         xfc=1
    #         yfc=1
    #     else :
    #         cfc=191
    #         xfc=1
    #         yfc=0.75
    #
    #     #根据主偏角调整参数
    #     main_arc=request.POST.get('main_arc')
    #     if main_arc=="a":
    #         kkfc=1.08
    #     elif main_arc=="b":
    #         kkfc=1
    #     elif main_arc=="c":
    #         kkfc=0.94
    #     elif main_arc=="d":
    #         kkfc=0.92
    #     else :
    #         kkfc=0.89
    #
    #     #根据刀具前角调整参数
    #     front_arc=request.POST.get('front_arc')
    #     if front_arc=="a":
    #         klfc=1.25
    #     elif front_arc=="b":
    #         klfc=1.2
    #     elif front_arc=="c":
    #         klfc=1.1
    #     elif front_arc=="d":
    #         klfc=1
    #     else :
    #         klfc=0.9
    #
    #     name=request.COOKIES.get('name')
    #     password=request.COOKIES.get('password')
    #     if exp_id==1:
    #         ret=render(request,'hitvmm/exp_1_2.html',{'cfc':cfc,'xfc':xfc,'yfc':yfc,'kkfc':kkfc,'klfc':klfc,'knfc':knfc,'krfc':krfc,'name':name,'password':password})
    #     if exp_id==2:
    #         ret=render(request,'hitvmm/exp_1_2.html',{'cfc':cfc,'xfc':xfc,'yfc':yfc,'kkfc':kkfc,'klfc':klfc,'knfc':knfc,'krfc':krfc,'name':name,'password':password})
    #     if exp_id==3:
    #         ret=render(request,'hitvmm/exp_1_2.html',{'cfc':cfc,'xfc':xfc,'yfc':yfc,'kkfc':kkfc,'klfc':klfc,'knfc':knfc,'krfc':krfc,'name':name,'password':password})
    #     #将参数存进cookie
    #     ret.set_cookie('cfc', cfc)
    #     ret.set_cookie('xfc', xfc)
    #     ret.set_cookie('yfc', yfc)
    #     ret.set_cookie('kkfc', kkfc)
    #     ret.set_cookie('klfc', klfc)
    #     ret.set_cookie('knfc', knfc)
    #     ret.set_cookie('krfc', krfc)
    #
    #     return ret

#实验1操作第2步页面
def exp_opr_1_3(request):
    #从cookie中取参数
    cfc=request.COOKIES.get('cfc')
    xfc=request.COOKIES.get('xfc')
    yfc=request.COOKIES.get('yfc')
    kkfc=request.COOKIES.get('kkfc')
    klfc=request.COOKIES.get('klfc')
    knfc=request.COOKIES.get('knfc')
    krfc=request.COOKIES.get('krfc')

    name=request.COOKIES.get('name')
    password=request.COOKIES.get('password')

    return render(request,'hitvmm/exp_1_3.html',{'cfc':cfc,'xfc':xfc,'yfc':yfc,'kkfc':kkfc,'klfc':klfc,'knfc':knfc,'krfc':krfc,'name':name,'password':password})

#实验1操作第3步页面
def exp_opr_1_4(request):
    #从cookie中取参数
    cfc=request.COOKIES.get('cfc')
    xfc=request.COOKIES.get('xfc')
    yfc=request.COOKIES.get('yfc')
    kkfc=request.COOKIES.get('kkfc')
    klfc=request.COOKIES.get('klfc')
    knfc=request.COOKIES.get('knfc')
    krfc=request.COOKIES.get('krfc')

    name=request.COOKIES.get('name')

hitvmm/templates/hitvmm/exp_1_1.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
    <script src="{% static 'jquery3.3.1.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/plugins/pace.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

    <script type="text/javascript" src="{% static 'js/plugins/bootstrap-datepicker.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/select2.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/bootstrap-datepicker.min.js' %}"></script>
    <script type="text/javascript">
      $('#sl').click(function(){
      	$('#tl').loadingBtn();
      	$('#tb').loadingBtn({ text : "Signing In"});
      });

      $('#el').click(function(){
      	$('#tl').loadingBtnComplete();
      	$('#tb').loadingBtnComplete({ html : "Sign In"});
      });

      $('#demoDate').datepicker({
      	format: "dd/mm/yyyy",
      	autoclose: true,
      	todayHighlight: true
      });

      $('#demoSelect').select2();
    </script>





    <title>切削用量对切削力的影响</title>

  </head>
  <body class="sidebar-mini fixed">
    <div class="wrapper">
      <!-- Navbar-->
      <header class="main-header hidden-print"><a class="logo" href="{% url 'hitvmm:index'%}">Virtual Machining Lab 3.0</a>
        <nav class="navbar navbar-static-top">
          <!-- Navbar Right Menu-->
          <div class="navbar-custom-menu">
            <div style="margin-top:15px;">
              <center>

                <h4>切削用量对切削力的影响</h4>
              </center>


        </nav>
      </header>
      <!-- Side-Nav-->
      <aside class="main-sidebar hidden-print">
        <section class="sidebar">
          <div class="user-panel">
            <div class="pull-left image"><img class="img-circle" src="{% static 'pic/head.jpg' %}" alt="User Image"></div>
            <div class="pull-left info">
              <p>{{name}}</p>
                <a href="{% url 'hitvmm:login'%}">退出登录</a>
            </div>
          </div>
          <!-- Sidebar Menu-->
          <ul class="sidebar-menu">
            <li><a href="{% url 'hitvmm:index'%}"><i class="fa fa-laptop"></i><span>实验预习</span></a></li>
            <li class="active"><a href="{% url 'hitvmm:exp_opr'%}"><i class="fa fa-dashboard"></i><span>实验操作</span></a></li>
            <li><a href="{% url 'hitvmm:report'%}"><i class="fa fa-file-text"></i><span>实验报告</span></a></li>
          </ul>
        </section>
      </aside>
      <div class="content-wrapper">

        <div class="row">
          <div class="col-md-6">
            <div class="card">
              <h3 class="card-title">选择实验参数</h3>
              <div class="card-footer">
              </div>
              <!--Radio Button Markup-->
              <div class="row">
                <div class="col-lg-12">
                  <div class="well bs-component">
                    <form class="form-horizontal" action="{% url 'hitvmm:exp_opr_1_2'%}" method="post">

                    {% csrf_token %}
                      <fieldset>

                      <div class="form-group">
                        <label class="col-lg-2 control-label">工件材料</label>
                        <div class="col-lg-10">
                          <div class="radio">
                            <label>
                              <input type="radio" name="workpiece_material" value="a" checked="checked" >45钢
                            </label>
                          </div>
                        </div>
                      </div>
                      <div class="card-footer">
                      <div class="form-group">
                        <label class="col-lg-2 control-label">刀具材料</label>
                        <div class="col-lg-10">
                          <div class="radio">
                            <label>
                              <input type="radio" name="tool_material" value="a" checked="checked">硬质合金
                            </label>
                          </div>
                        </div>
                      </div>
                      </div>
                      <div class="card-footer">
                      <div class="form-group">
                        <label class="col-lg-2 control-label">加工形式</label>
                        <div class="col-lg-10">
                          <div class="radio">
                            <label>
                              <input type="radio" name="machining_form" value="a" checked="checked">外圆纵车
                            </label>
                          </div>
                          <div class="radio">
                            <label>
                              <input type="radio" name="machining_form" value="b">切槽及切断
                            </label>
                          </div>
                          <div class="radio">
                            <label>
                              <input type="radio" name="machining_form" value="c">成形车削
                            </label>
                          </div>
                        </div>
                      </div>
                      </div>

                      <div class="card-footer">
                      <div class="form-group">
                        <label class="col-lg-2 control-label">刀具参数</label>

                        <div class="col-lg-10">
                          <table class="table table-hover">

                            <tbody>
                              <tr>
                                <td>主偏角:</td>
                                <td><input type="radio" name="main_arc" value="a" checked="checked"> 30°</td>
                                <td><input type="radio" name="main_arc" value="b"> 45°</td>
                                <td><input type="radio" name="main_arc" value="c"> 60°</td>
                                <td><input type="radio" name="main_arc" value="d"> 75°</td>
                                <td></td><td></td>
                              </tr>
                              <tr>
                                <td>前角：</td>
                                <td><input type="radio" name="front_arc" value="a" checked="checked"> -15°</td>
                                <td><input type="radio" name="front_arc" value="b"> -10°</td>
                                <td><input type="radio" name="front_arc" value="c"> 0°</td>
                                <td><input type="radio" name="front_arc" value="d"> 10°</td>
                                <td><input type="radio" name="front_arc" value="e"> 20°</td>
                                <td></td>
                              </tr>
                              <tr>
                                <td>刃倾角：</td>
                                <td><input type="radio" name="blade_arc" value="a" checked="checked"> 5°</td>
                                <td><input type="radio" name="blade_arc" value="b"> 0°</td>
                                <td><input type="radio" name="blade_arc" value="c"> -5°</td>
                                <td><input type="radio" name="blade_arc" value="d"> -10°</td>
                                <td><input type="radio" name="blade_arc" value="e"> -15°</td>
                                <td></td>

                              </tr>
                              <tr>
                                <td>刀尖圆弧半径：</td>
                                <td><input type="radio" name="tool_arc" value="a" checked="checked"> 0.25mm</td>
                                <td><input type="radio" name="tool_arc" value="b"> 0.5mm</td>
                                <td><input type="radio" name="tool_arc" value="c"> 0.75mm</td>
                                <td><input type="radio" name="tool_arc" value="d"> 1mm</td>
                                <td><input type="radio" name="tool_arc" value="e"> 1.5mm</td>
                                <td><input type="radio" name="tool_arc" value="f"> 2mm</td>

                              </tr>
                            </tbody>
                          </table>




                        </div>


                    </div>
                    </div>


                      <div class="card-footer">
                      </div>
                      <center><input class="btn btn-primary" type="submit" value="确认参数"></center>
                  </form>
                  </fieldset>
                  </div>
                </div>
              </div>
            </div>

          </div>
       </div>
    </div>

  </body>
</html>

hitvmm/templates/hitvmm/exp_opr.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <script src="{% static 'jquery3.3.1.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/plugins/pace.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>


    <title>实验操作</title>

  </head>
  <body class="sidebar-mini fixed">
    <div class="wrapper">
      <!-- Navbar-->
      <header class="main-header hidden-print"><a class="logo" href="{% url 'hitvmm:index'%}">Virtual Machining Lab 3.0</a>
        <nav class="navbar navbar-static-top">
          <!-- Navbar Right Menu-->
          <div class="navbar-custom-menu">
            <div style="margin-top:15px;">
              <center>

                <h4>实验操作</h4>
              </center>


        </nav>
      </header>
      <!-- Side-Nav-->
      <aside class="main-sidebar hidden-print">
        <section class="sidebar">
          <div class="user-panel">
            <div class="pull-left image"><img class="img-circle" src="{% static 'pic/head.jpg' %}" alt="User Image"></div>
            <div class="pull-left info">
              <p>{{name}}</p>
                <a href="{% url 'hitvmm:login'%}">退出登录</a>
            </div>
          </div>
          <!-- Sidebar Menu-->
          <ul class="sidebar-menu">
            <li><a href="{% url 'hitvmm:index'%}"><i class="fa fa-laptop"></i><span>实验预习</span></a></li>
            <li class="active"><a href="{% url 'hitvmm:exp_opr'%}"><i class="fa fa-dashboard"></i><span>实验操作</span></a></li>
            <li><a href="{% url 'hitvmm:report'%}"><i class="fa fa-file-text"></i><span>实验报告</span></a></li>
          </ul>
        </section>
      </aside>
      <div class="content-wrapper">

        <div class="row">
          <div class="col-md-6">
            <div class="card">
              <h4 class="card-title">切削用量对切削力的影响 </h4>
              <div class="card-body">本实验的目的是研究在车床车削工件过程中，“背吃刀量”、“进给量”和“切削速度”三种切削用量和主切削力大小之间的关系。</div>
              <div class="card-body">实验分为三个子实验，你需要依次完成实验操作并下载实验结果。</div>
              <div class="card-body">实验结束后，请完成实验报告并转换成PDF文档在系统的“实验报告”板块上传实验报告。</div>
              <div class="card-footer"><a class="btn btn-primary" href="{% url 'hitvmm:exp_opr_1_1'%}">进入实验</a></div>
            </div>
            <div class="card">
              <h4 class="card-title">切削用量对切削温度的影响 </h4>
              <div class="card-body">本实验的目的是研究在车床车削工件过程中，“背吃刀量”、“进给量”和“切削速度”三种切削用量和刀尖处切削温度高低之间的关系。</div>
              <div class="card-body">实验分为三个子实验，你需要依次完成实验操作并下载实验结果。</div>
              <div class="card-body">实验结束后，请完成实验报告并转换成PDF文档在系统的“实验报告”板块上传实验报告。</div>
                            <div class="card-footer"><a class="btn btn-primary" href="{% url 'hitvmm:exp_opr_2_1'%}">进入实验</a> </div>
            </div>
            <div class="card">
              <h4 class="card-title">切削用量对表面粗糙度的影响 </h4>
              <div class="card-body">本实验的目的是研究在车床车削工件过程中，“背吃刀量”、“进给量”和“切削速度”三种切削用量和加工面表面粗糙度之间的关系。</div>
              <div class="card-body">实你需要完成实验操作并下载实验结果。</div>
              <div class="card-body">实验结束后，请完成实验报告并转换成PDF文档在系统的“实验报告”板块上传实验报告。</div>
                              <div class="card-footer"><a class="btn btn-primary" href="{% url 'hitvmm:exp_opr_3_1'%}">进入实验</a></div>
            </div>
          </div>
       </div>
    </div>

  </body>
</html>

hitvmm/templates/hitvmm/toindex.html
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="Refresh" content="0,{% url 'hitvmm:index'%}">


    <title>首页</title>

  </head>
  <body>
    正在跳转到首页
  </body>
</html>